### ISSUE TITLE
CKAN on Openshift

### ISSUE THREAD

**Issue by dagniel** [ckan/ideas#226]
I've just finished an initial configuration that sets-up CKAN on Openshift. More specifically the community version: OKD 3.10.

I will have to get some formal acceptance before making this publicly available, but I was wondering if it would be of use.

I've mostly followed and adapted/changed the instructions for the Docker Compose version and the underlying feeling was that the procedure is mostly aimed for the developer that wants to have direct access to the container and switch/add/remove contents and or configuration without necessarily having in mind automation and replication.
So I thought to maybe ask if it would be of any help. Are there any issues that you think it might solve regarding anything related to the community around the CKAN project?

Thanks!

**Comment by trumbaut** [comment]
That would be very helpful indeed. We are thinking about running CKAN within OpenShift too. Would you mind to share this configuration? Thanks in advance!

**Comment by dagniel** [comment]
Hi and sorry for late reply!

I'll try to begin on working on the public configuration, with the main issues being the refactoring, see how I can go about my use of custom builds/images and, generally, trying to make it useable for people with a vanilla version of Openshift/OKD/minishift without going into the details of the platform.

Will update this issue once I have something set up.

**Comment by dagniel** [comment]
I'm about to finish a public version of configuring the CKAN stack to run on Openshift and was going to the top level versions of the different components.

I'd appreciate if you can give some input about them....whether to switch to different versions or different sources, if you have bad experiences with using different versions,  or other info etc...

The repo (rather complete, but still work-in-progress and not fully tested) holding the config is: https://github.com/dagniel/ckan-on-openshift.git
- **CKAN** from **ckan-2.8.2 tag** of the official repo at https://github.com/ckan/ckan.git
- **PostgreSQL** with GIS for version **9.6(12 and 14)** based on https://github.com/CrunchyData/crunchy-containers.git
- **Redis 3.2** from docker.io/centos/redis-32-centos7:3.2
- **Solr** based on docker.io/solr:**6.6.2(and 6.6.5)**
- **Datapusher** from **0.0.15 tag** of the repo at https://github.com/ckan/datapusher.git (the image presented in the docs seemed to be based on a old repository...)

Thank you!

**Comment by ssbeaver** [comment]
Hi I found that you already created project for CKAN on Openshift in https://github.com/dagniel/ckan-on-openshift sinc Aug 2019
Does your implementation done successfully?

We are also implementing CKAN on Openshift environement. 
Can I use your project to implement on the production?
Any concern or recommendation for this?
Please advise.

**Comment by dagniel** [comment]
I haven't worked on it for a couple of months now.
The config is done for 3.11 and tested with OKD. Last time I checked it deployed successfully. A quick way to test it is by using the learning portal of Openshift: https://learn.openshift.com/playgrounds/ and following the steps described on the README.

This config isn't meant to be production ready, but rather as a starting point for using CKAN on Openshift. It deploys one of each components(so no HA for Postgres, for example), with basic configuration of the containers. 
Another issue would be related to container security vulnerabilities identified by quay for the centOS based ones. The docker builds would require some tweaks for this.

As advice, wouldn't know....maybe test it first, see how/if it works for you. 

For a production level variant you can have a look at https://github.com/ckan/ideas-and-roadmap/issues/206#issuecomment-445047125 It's not Openshift specific but much more through/complex.

**Comment by rufuspollock** [comment]
FIXED. @dagniel thank you for sharing and this is really useful 👏 👏 . I'm closing this issue now as we have a resolution and I'm adding this to Deployment section of Awesome CKAN: https://github.com/ckan/awesome-ckan#deployment

Please feel free to keep updating this issue or the awesome repo 😄
