### ISSUE TITLE
Allowing any user to edit any data set.

### ISSUE THREAD

**Issue by rdahis** [ckan/ideas#237]
I have created organizations, each of which own a certain number of data sets. I would like to allow for any user, who registered via the web, to edit any data set freely.

I see this done by:
1- Adding every user to every organization as 'editor'. This is a pain since it has to be done by hand, each user at a time, for every organization.
2- Finding some configuration in CKAN to allow this type of permission. I don't know if that's possible, though.

Any ideas?

**Comment by rufuspollock** [comment]
I believe you easily create an extension that would set custom permissions like this. Feel free to reopen if you need more guidance.
