### ISSUE TITLE
Awesome CKAN repo

### ISSUE THREAD

**Issue by rufuspollock** [ckan/ideas#246]

**Comment by tino097** [comment]
we have started something similar few years ago https://github.com/ZoranPandovski/awesome-ckan-extensions

**Comment by ZoranPandovski** [comment]
Feel free to contribute to it, or if you are interested in improving I can transfer ownership to the CKAN org.

**Comment by rufuspollock** [comment]
Yes, let's transfer this to the ckan org if you are happy with that 😄

**Comment by rufuspollock** [comment]
@ZoranPandovski any thoughts?

**Comment by amercader** [comment]
@ZoranPandovski We'd like to start an "awesome" repo on the main ckan org (https://github.com/ckan/awesome-ckan) are you happy to start it off with yours? There's lots of great stuff in there. I can give you access to it so you can push or if it's easier we can just copy your files.

**Comment by tino097** [comment]
@amercader @rufuspollock @ZoranPandovski i have rights to push to the newly created repo

**Comment by ZoranPandovski** [comment]
I will push everything there @amercader

**Comment by amercader** [comment]
@rufuspollock @ZoranPandovski @tino097 many thanks! You should all have write access to that repo now

**Comment by rufuspollock** [comment]
FIXED. Repo is live https://github.com/ckan/awesome-ckan - Thanks everyone and let's start contributing 😄
