### ISSUE TITLE
Apply for Google Funding

### ISSUE THREAD

**Issue by TkTech** [ckan/ideas#265]
- Google Post: https://opensource.googleblog.com/2020/12/finding-critical-open-source-projects.html
- Python Top 200: https://www.googleapis.com/download/storage/v1/b/ossf-criticality-score/o/python_top_200.csv?generation=1607667470204905&alt=media

Under this new initiative, Google will be funding open source projects that they deem to be "critical", based on a formula that you can find in the project's Github repo, [here](https://github.com/ossf/criticality_score).

The main ckan/ckan repository comes in at number 35, making it very likely that the project would qualify. It may be worth reaching out and seeing what level of support is available, as levels aren't really mention. Is this enough to cover the domain name renwal and other infrastructure, or enough to hire a full time junior or senior dev?

**Comment by wardi** [comment]
@pwalsh @Starl3n is this something that the stewards would apply for? The tech team isn't set up to handle finances but I'm sure we have suggestions for how some funding could be spent.

**Comment by Starl3n** [comment]
Yes, I would think so.  I'll look into the detail on Monday.

*STEVEN DE COSTA *|
*CHAIRMAN*www.linkdigital.com.au

<https://linkdigital.com.au/>

<https://linkedin.com/company/link-digital> <https://github.com/datashades>
<https://twitter.com/link_digital> <https://www.facebook.com/LinkDigital/>
